const SUPABASE_URL="https://dprulohylwgzmetgrywj.supabase.co";
const SUPABASE_KEY="sb_publishable_gNWkc787SxA7U76No3A4kg_XHP0x2j4";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const slugify=v=>String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const date=v=>v?new Date(v).toLocaleDateString("en-NG",{year:"numeric",month:"short",day:"numeric"}):"—";
let state={user:null,stories:[],people:[],submissions:[],claims:[],ads:[],categories:[],settings:[],slots:[],homepageSections:[]};

async function boot(){
 const {data:{session}}=await db.auth.getSession();
 if(!session){showLogin();return}
 const {data:{user}}=await db.auth.getUser();
 const admin=await db.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();
 if(admin.error||!admin.data){await db.auth.signOut();showLogin();$("#loginMsg").textContent="This account is not an authorized administrator.";return}
 state.user=user;$("#loginView").classList.add("hidden");$("#adminView").classList.remove("hidden");await refresh();
}
function showLogin(){$("#loginView").classList.remove("hidden");$("#adminView").classList.add("hidden")}
async function refresh(){await Promise.all([loadStories(),loadPeople(),loadSubmissions(),loadClaims(),loadAds(),loadCategories(),loadSettings(),loadSlots(),loadHomepageSections()]);renderAll()}
async function loadStories(){const r=await db.from("posts").select("*").order("created_at",{ascending:false});state.stories=r.data||[]}
async function loadCelebrity(){const r=await db.from("posts").select("id,title,is_published,published_at,slug").eq("category_id","f08e1fe3-76c6-47d9-9dd1-bd062b5ae326").order("published_at",{ascending:false});state.celebrity=r.data||[]}
async function loadPeople(){const r=await db.from("people_profiles").select("*").order("created_at",{ascending:false});state.people=r.data||[]}
async function loadSubmissions(){const r=await db.from("profile_submissions").select("*").order("created_at",{ascending:false});state.submissions=r.data||[]}
async function loadClaims(){const r=await db.from("profile_claims").select("*,people_profiles(display_name,slug)").order("submitted_at",{ascending:false});state.claims=r.data||[]}
async function loadAds(){const r=await db.from("ad_campaigns").select("*").order("created_at",{ascending:false});state.ads=r.data||[]}
async function loadCategories(){const r=await db.from("post_categories").select("*").eq("is_active",true).order("sort_order");state.categories=r.data||[]}
async function loadSettings(){const r=await db.from("site_settings").select("*").order("setting_key");state.settings=r.data||[]}
async function loadSlots(){const r=await db.from("ad_slots").select("*").order("name");state.slots=r.data||[]}
async function loadHomepageSections(){const r=await db.from("homepage_sections").select("*").order("sort_order");state.homepageSections=r.data||[]}

function renderAll(){renderStats();renderQueue();renderStories();renderPeople();renderSubmissions();renderClaims();renderAds();renderMedia();renderSettings();renderHomepageCMS();renderCelebrityAdmin()}
function renderStats(){
 const pending=[...state.submissions,...state.claims].filter(x=>["pending","under_review"].includes(x.status)).length;
 $("#stats").innerHTML=[["Stories",state.stories.length],["Published",state.stories.filter(x=>x.is_published).length],["People",state.people.length],["Review queue",pending]].map(x=>'<div class="stat"><strong>'+x[1]+'</strong><span>'+x[0]+'</span></div>').join("");
 const clicks=state.ads.reduce((n,x)=>n+Number(x.clicks||0),0),imps=state.ads.reduce((n,x)=>n+Number(x.impressions||0),0);
 $("#adStats").innerHTML=[["Campaigns",state.ads.length],["Active",state.ads.filter(x=>x.status==="active").length],["Impressions",imps],["Clicks",clicks]].map(x=>'<div class="stat"><strong>'+x[1]+'</strong><span>'+x[0]+'</span></div>').join("");
}
function renderQueue(){const items=[...state.submissions.map(x=>({kind:"Profile",name:x.name,status:x.status})),...state.claims.map(x=>({kind:"Claim",name:x.claimant_name,status:x.status}))].filter(x=>["pending","under_review"].includes(x.status));$("#queue").innerHTML=items.length?items.slice(0,10).map(x=>'<div style="padding:10px 0;border-bottom:1px solid #eee"><b>'+esc(x.kind)+'</b> · '+esc(x.name)+' <span class="badge">'+esc(x.status)+'</span></div>').join(""):"<p>No pending review items.</p>"}
function renderStories(){const rows=state.stories.map(x=>'<tr><td><b>'+esc(x.title)+'</b><br><small>'+esc(x.slug||"")+'</small></td><td>'+esc(x.content_type)+'</td><td><span class="badge '+(x.is_published?"good":"")+'">'+(x.is_published?"published":"draft")+'</span></td><td>'+date(x.published_at)+'</td><td><div class="actions"><button data-edit-story="'+x.id+'">Edit</button><button data-toggle-story="'+x.id+'">'+(x.is_published?"Unpublish":"Publish")+'</button><button data-delete-story="'+x.id+'">Delete</button></div></td></tr>').join("");$("#storiesTable").innerHTML=rows||'<tr><td colspan="5">No stories yet.</td></tr>'}
function renderPeople(){const rows=state.people.map(x=>'<tr><td><b>'+esc(x.display_name)+'</b><br><small>'+esc(x.slug)+'</small></td><td>'+esc(x.person_type)+'</td><td><span class="badge '+(x.is_published?"good":"")+'">'+(x.is_published?"published":"draft")+'</span></td><td>'+(x.is_verified?"✓ Yes":"No")+'</td><td><div class="actions"><button data-edit-person="'+x.id+'">Edit</button><button data-toggle-person="'+x.id+'">'+(x.is_published?"Unpublish":"Publish")+'</button><button data-verify-person="'+x.id+'">'+(x.is_verified?"Unverify":"Verify")+'</button></div></td></tr>').join("");$("#peopleTable").innerHTML=rows||'<tr><td colspan="5">No profiles yet.</td></tr>'}
function renderSubmissions(){const rows=state.submissions.map(x=>'<tr><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.profession)+'</td><td><span class="badge">'+esc(x.status)+'</span></td><td>'+date(x.created_at)+'</td><td><div class="actions"><button data-sub="'+x.id+'">Review</button></div></td></tr>').join("");$("#submissionsTable").innerHTML=rows||'<tr><td colspan="5">No submissions.</td></tr>'}
function renderClaims(){const rows=state.claims.map(x=>'<tr><td><b>'+esc(x.claimant_name)+'</b><br><small>'+esc(x.claimant_email)+'</small></td><td>'+esc(x.people_profiles?.display_name||"—")+'</td><td><span class="badge">'+esc(x.status)+'</span></td><td>'+(x.proof_url?'<a class="linkish" href="'+esc(x.proof_url)+'" target="_blank" rel="noopener">Open proof</a>':"—")+'</td><td><div class="actions"><button data-claim="'+x.id+'">Review</button></div></td></tr>').join("");$("#claimsTable").innerHTML=rows||'<tr><td colspan="5">No claims.</td></tr>'}
function renderAds(){const rows=state.ads.map(x=>'<tr><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.advertiser_name)+'</td><td>'+esc(x.campaign_type)+'</td><td><span class="badge '+(x.status==="active"?"good":"")+'">'+esc(x.status)+'</span></td><td>'+Number(x.clicks||0)+'</td><td><div class="actions"><button data-edit-ad="'+x.id+'">Edit</button></div></td></tr>').join("");$("#adsTable").innerHTML=rows||'<tr><td colspan="6">No campaigns yet.</td></tr>'}
function renderMedia(){db.storage.from("naija-media").list("",{limit:100,sortBy:{column:"created_at",order:"desc"}}).then(({data})=>{$("#mediaList").innerHTML=(data||[]).map(x=>{const url=db.storage.from("naija-media").getPublicUrl(x.name).data.publicUrl;const media=x.metadata?.mimetype?.startsWith("video/")?'<video src="'+esc(url)+'" controls></video>':'<img src="'+esc(url)+'" alt="'+esc(x.name)+'">';return '<div class="media-item">'+media+'<small>'+esc(x.name)+'</small></div>'}).join("")||'<div class="card">No media uploaded yet.</div>'})}
function renderCelebrityAdmin(){const t=$("#celebrityAdminTable"),m=$("#celebrityAdminMsg");if(!t)return;t.innerHTML=state.celebrity.map(x=>`<tr><td><strong>${esc(x.title)}</strong></td><td>${x.is_published?"Published":"Draft"}</td><td>${x.published_at?new Date(x.published_at).toLocaleDateString():"—"}</td></tr>`).join("");if(m)m.textContent=state.celebrity.length+" archived celebrity records. Public Celebrity Desk uses real source articles."}
function renderSettings(){$("#settingsForm").innerHTML=state.settings.map(x=>'<label>'+esc(x.setting_key)+'<input data-setting="'+esc(x.setting_key)+'" value="'+esc(x.setting_value||"")+'"></label>').join("")||"<p>No settings available.</p>"}
function settingValue(key){const x=state.settings.find(s=>s.setting_key===key);return x?.setting_value||""}
function renderHomepageCMS(){
 const keys=["site_name","site_tagline","hero_kicker","hero_title","hero_description","hero_story_slug","primary_nav","hot_stories","footer_description","footer_copyright","theme_green","theme_black","theme_paper"];
 const labels={site_name:"Site name",site_tagline:"Site tagline",hero_kicker:"Hero kicker",hero_title:"Hero title",hero_description:"Hero description",hero_story_slug:"Featured story slug (optional)",primary_nav:"Primary navigation (use | between items)",hot_stories:"Hot Stories links (use | between items)",footer_description:"Footer description",footer_copyright:"Footer copyright text",theme_green:"Green accent",theme_black:"Black",theme_paper:"Paper background"};
 const g=$("#homepageGlobalForm"); if(g)g.innerHTML=keys.map(k=>'<label>'+labels[k]+'<input data-home-setting="'+k+'" value="'+esc(settingValue(k))+'"></label>').join("");
 const box=$("#homepageSectionsForm"); if(!box)return;
 box.innerHTML=state.homepageSections.map((x,i)=>'<div class="cms-row" data-section-id="'+x.id+'"><div class="cms-drag">'+(i+1)+'</div><label>Section title<input data-sec-title value="'+esc(x.title||"")+'"></label><label>Kicker<input data-sec-kicker value="'+esc(x.kicker||"")+'"></label><label>Link<input data-sec-href value="'+esc(x.href||"")+'"></label><label>Order<input data-sec-order type="number" value="'+Number(x.sort_order||0)+'"></label><label>Items<input data-sec-max type="number" min="1" max="30" value="'+Number(x.max_items||6)+'"></label><label class="checkline"><input data-sec-enabled type="checkbox" '+(x.enabled?"checked":"")+'> Visible</label><button class="danger" data-remove-section>Hide permanently</button></div>').join("")||'<p>No homepage sections configured.</p>';
}
async function saveHomepage(){
 const msg=$("#homepageMsg"); if(msg)msg.textContent="Saving…";
 for(const i of document.querySelectorAll("[data-home-setting]")){
   const r=await db.from("site_settings").update({setting_value:i.value,updated_at:new Date().toISOString()}).eq("setting_key",i.dataset.homeSetting);
   if(r.error){if(msg)msg.textContent=r.error.message;return}
 }
 for(const row of document.querySelectorAll("[data-section-id]")){
   const payload={title:row.querySelector("[data-sec-title]").value.trim(),kicker:row.querySelector("[data-sec-kicker]").value.trim(),href:row.querySelector("[data-sec-href]").value.trim(),sort_order:Number(row.querySelector("[data-sec-order]").value)||0,max_items:Math.min(30,Math.max(1,Number(row.querySelector("[data-sec-max]").value)||6)),enabled:row.querySelector("[data-sec-enabled]").checked,updated_at:new Date().toISOString()};
   const r=await db.from("homepage_sections").update(payload).eq("id",row.dataset.sectionId); if(r.error){if(msg)msg.textContent=r.error.message;return}
 }
 await refresh(); if(msg)msg.textContent="Homepage controls saved. Refresh the public site to see the changes.";
}
async function addHomepageSection(){
 const title=prompt("Section title"); if(!title)return;
 const key=slugify(title)+"_"+Date.now();
 const r=await db.from("homepage_sections").insert({section_key:key,title,kicker:"CUSTOM",href:"#",sort_order:(state.homepageSections.at(-1)?.sort_order||0)+10,layout:"grid",max_items:6,settings:{}}); if(r.error)alert(r.error.message); else await refresh();
}

function storyEditor(x={}){const cats=state.categories.map(c=>'<option value="'+c.id+'" '+(x.category_id===c.id?"selected":"")+'>'+esc(c.name)+'</option>').join("");$("#storyEditor").innerHTML='<div class="editor"><div class="eyebrow">STORY EDITOR</div><div class="editor-grid"><label>Title<input id="seTitle" value="'+esc(x.title||"")+'"></label><label>Slug<input id="seSlug" value="'+esc(x.slug||"")+'"></label><label>Category<select id="seCat"><option value="">Uncategorised</option>'+cats+'</select></label><label>Content type<select id="seType">'+["news","feature","interview","press_release","opinion","review","video","other"].map(v=>'<option '+(x.content_type===v?"selected":"")+'>'+v+'</option>').join("")+'</select></label><label class="wide">Excerpt<textarea id="seExcerpt">'+esc(x.excerpt||"")+'</textarea></label><label class="wide">Content<textarea id="seContent">'+esc(x.content||"")+'</textarea></label><label>Featured image URL<input id="seImage" value="'+esc(x.featured_image_url||"")+'"></label><label>Author<input id="seAuthor" value="'+esc(x.author||"Naija Newspaper")+'"></label><label>Meta title<input id="seMetaTitle" value="'+esc(x.meta_title||"")+'"></label><label>Meta description<input id="seMetaDesc" value="'+esc(x.meta_description||"")+'"></label><label class="checkline"><input id="seSponsored" type="checkbox" '+(x.sponsored?"checked":"")+'> Sponsored content</label><label>Sponsored by<input id="seSponsor" value="'+esc(x.sponsor_name||"")+'"></label></div><div class="actions"><button class="primary" id="saveStoryBtn">Save draft</button><button class="secondary" id="publishStoryBtn">Save & publish</button><button class="secondary" id="cancelStoryBtn">Cancel</button></div></div>';$("#storyEditor").classList.remove("hidden");$("#seTitle").addEventListener("input",()=>{if(!x.id)$("#seSlug").value=slugify($("#seTitle").value)});$("#saveStoryBtn").onclick=()=>saveStory(x,false);$("#publishStoryBtn").onclick=()=>saveStory(x,true);$("#cancelStoryBtn").onclick=()=>$("#storyEditor").classList.add("hidden")}
async function saveStory(x,publish){const title=$("#seTitle").value.trim();if(!title){alert("Title is required.");return}const payload={title,slug:slugify($("#seSlug").value||title),category_id:$("#seCat").value||null,content_type:$("#seType").value,excerpt:$("#seExcerpt").value.trim(),content:$("#seContent").value,featured_image_url:$("#seImage").value.trim()||null,author:$("#seAuthor").value.trim()||"Naija Newspaper",meta_title:$("#seMetaTitle").value.trim()||null,meta_description:$("#seMetaDesc").value.trim()||null,sponsored:$("#seSponsored").checked,sponsor_name:$("#seSponsor").value.trim()||null,is_published:publish,published_at:publish?(x.published_at||new Date().toISOString()):x.published_at||null};const r=x.id?await db.from("posts").update(payload).eq("id",x.id):await db.from("posts").insert(payload);if(r.error){alert(r.error.message);return}$("#storyEditor").classList.add("hidden");await refresh()}
function personEditor(x={}){const types=["artist","creator","influencer","actor","athlete","entrepreneur","podcaster","comedian","journalist","public_figure","professional","other"];$("#personEditor").innerHTML='<div class="editor"><div class="eyebrow">PROFILE EDITOR</div><div class="editor-grid"><label>Display name<input id="peName" value="'+esc(x.display_name||"")+'"></label><label>Slug<input id="peSlug" value="'+esc(x.slug||"")+'"></label><label>Type<select id="peType">'+types.map(v=>'<option '+(x.person_type===v?"selected":"")+'>'+v+'</option>').join("")+'</select></label><label>Category<input id="peCategory" value="'+esc(x.category||"")+'"></label><label>Headline<input id="peHeadline" value="'+esc(x.headline||"")+'"></label><label>Location<input id="peLocation" value="'+esc(x.location||"")+'"></label><label>Country<input id="peCountry" value="'+esc(x.country||"")+'"></label><label>Birth date<input id="peBirth" type="date" value="'+esc(x.birth_date||"")+'"></label><label>Profile image URL<input id="peImage" value="'+esc(x.profile_image_url||"")+'"></label><label>Official website<input id="peWeb" value="'+esc(x.official_website_url||"")+'"></label><label class="wide">Short bio<textarea id="peShort">'+esc(x.short_bio||"")+'</textarea></label><label class="wide">Biography<textarea id="peBio">'+esc(x.bio||"")+'</textarea></label><label>Meta title<input id="peMetaTitle" value="'+esc(x.meta_title||"")+'"></label><label>Meta description<input id="peMetaDesc" value="'+esc(x.meta_description||"")+'"></label><label class="wide">SameAs URLs (one per line)<textarea id="peSame">'+esc(Array.isArray(x.same_as)?x.same_as.join("\n"):"")+'</textarea></label></div><div class="actions"><button class="primary" id="savePersonBtn">Save draft</button><button class="secondary" id="publishPersonBtn">Save & publish</button><button class="secondary" id="cancelPersonBtn">Cancel</button></div></div>';$("#personEditor").classList.remove("hidden");$("#peName").addEventListener("input",()=>{if(!x.id)$("#peSlug").value=slugify($("#peName").value)});$("#savePersonBtn").onclick=()=>savePerson(x,false);$("#publishPersonBtn").onclick=()=>savePerson(x,true);$("#cancelPersonBtn").onclick=()=>$("#personEditor").classList.add("hidden")}
async function savePerson(x,publish){const name=$("#peName").value.trim();if(!name){alert("Display name is required.");return}const payload={display_name:name,slug:slugify($("#peSlug").value||name),person_type:$("#peType").value,category:$("#peCategory").value.trim()||null,headline:$("#peHeadline").value.trim()||null,location:$("#peLocation").value.trim()||null,country:$("#peCountry").value.trim()||null,birth_date:$("#peBirth").value||null,profile_image_url:$("#peImage").value.trim()||null,official_website_url:$("#peWeb").value.trim()||null,short_bio:$("#peShort").value.trim()||null,bio:$("#peBio").value.trim()||null,meta_title:$("#peMetaTitle").value.trim()||null,meta_description:$("#peMetaDesc").value.trim()||null,same_as:$("#peSame").value.split(/\n+/).map(v=>v.trim()).filter(Boolean),is_published:publish};const r=x.id?await db.from("people_profiles").update(payload).eq("id",x.id):await db.from("people_profiles").insert(payload);if(r.error){alert(r.error.message);return}$("#personEditor").classList.add("hidden");await refresh()}
async function reviewSubmission(id){const x=state.submissions.find(v=>v.id===id);if(!x)return;const action=prompt("Type approve or reject. Optional reviewer note after a |");if(!action)return;const [decision,note=""]=action.split("|").map(v=>v.trim());if(!["approve","reject"].includes(decision))return alert("Use approve or reject.");const status=decision==="approve"?"approved":"rejected";if(decision==="approve"){const slug=slugify(x.name);const p=await db.from("people_profiles").insert({slug,display_name:x.name,headline:x.profession||x.category||null,person_type:"public_figure",category:x.category||null,bio:x.bio||null,short_bio:x.bio?String(x.bio).slice(0,240):null,official_website_url:x.website_url||null,profile_image_url:x.photo_url||null,is_published:false}).select().single();if(p.error){alert("Could not create profile: "+p.error.message);return}}const r=await db.from("profile_submissions").update({status,reviewer_user_id:state.user.id,reviewer_notes:note,reviewed_at:new Date().toISOString()}).eq("id",id);if(r.error)alert(r.error.message);else await refresh()}
async function reviewClaim(id){const x=state.claims.find(v=>v.id===id);if(!x)return;const action=prompt("Type approve or reject. Optional note after |");if(!action)return;const [decision,note=""]=action.split("|").map(v=>v.trim());if(!["approve","reject"].includes(decision))return alert("Use approve or reject.");const status=decision==="approve"?"approved":"rejected";const r=await db.from("profile_claims").update({status,reviewer_user_id:state.user.id,reviewer_notes:note,reviewed_at:new Date().toISOString()}).eq("id",id);if(r.error){alert(r.error.message);return}if(decision==="approve"&&x.person_id){const p=await db.from("people_profiles").update({is_verified:true,verified_at:new Date().toISOString(),verified_label:"Verified by Naija Newspaper"}).eq("id",x.person_id);if(p.error){alert("Claim approved, but profile verification update failed: "+p.error.message);return}}await refresh()}
function adEditor(x={}){const slots=state.slots.map(s=>'<option value="'+s.id+'" '+(x.slot_id===s.id?"selected":"")+'>'+esc(s.name)+'</option>').join("");$("#adEditor").innerHTML='<div class="editor"><div class="eyebrow">CAMPAIGN EDITOR</div><div class="editor-grid"><label>Name<input id="aeName" value="'+esc(x.name||"")+'"></label><label>Advertiser<input id="aeAdvertiser" value="'+esc(x.advertiser_name||"")+'"></label><label>Type<select id="aeType">'+["direct","sponsored","affiliate","network"].map(v=>'<option '+(x.campaign_type===v?"selected":"")+'>'+v+'</option>').join("")+'</select></label><label>Status<select id="aeStatus">'+["draft","pending","active","paused","completed","cancelled"].map(v=>'<option '+(x.status===v?"selected":"")+'>'+v+'</option>').join("")+'</select></label><label>Budget<input id="aeBudget" type="number" min="0" step="0.01" value="'+esc(x.budget||"")+'"></label><label>Currency<input id="aeCurrency" value="'+esc(x.currency||"NGN")+'"></label><label>Target URL<input id="aeTarget" value="'+esc(x.target_url||"")+'"></label><label>Creative URL<input id="aeCreative" value="'+esc(x.creative_url||"")+'"></label><label>Ad slot<select id="aeSlot"><option value="">None</option>'+slots+'</select></label><label class="wide">Notes<textarea id="aeNotes">'+esc(x.notes||"")+'</textarea></label></div><div class="actions"><button class="primary" id="saveAdBtn">Save campaign</button><button class="secondary" id="cancelAdBtn">Cancel</button></div></div>';$("#adEditor").classList.remove("hidden");$("#saveAdBtn").onclick=()=>saveAd(x);$("#cancelAdBtn").onclick=()=>$("#adEditor").classList.add("hidden")}
async function saveAd(x){const payload={name:$("#aeName").value.trim(),advertiser_name:$("#aeAdvertiser").value.trim()||null,campaign_type:$("#aeType").value,status:$("#aeStatus").value,budget:Number($("#aeBudget").value)||null,currency:$("#aeCurrency").value.trim()||"NGN",target_url:$("#aeTarget").value.trim()||null,creative_url:$("#aeCreative").value.trim()||null,slot_id:$("#aeSlot").value||null,notes:$("#aeNotes").value.trim()||null};if(!payload.name)return alert("Campaign name is required.");const r=x.id?await db.from("ad_campaigns").update(payload).eq("id",x.id):await db.from("ad_campaigns").insert(payload);if(r.error)alert(r.error.message);else{$("#adEditor").classList.add("hidden");await refresh()}}
async function toggle(table,id,field,value){const r=await db.from(table).update({[field]:value}).eq("id",id);if(r.error)alert(r.error.message);else await refresh()}
document.addEventListener("click",async e=>{const b=e.target.closest("[data-publish-celeb]");if(b){await db.from("posts").update({is_published:true,published_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",b.dataset.publishCeleb);await loadCelebrity();renderCelebrityAdmin()}if(e.target.id==="publishAllCelebrityBtn"){const r=await db.from("posts").update({is_published:true,published_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("category_id","f08e1fe3-76c6-47d9-9dd1-bd062b5ae326");if(r.error)$("#celebrityAdminMsg").textContent=r.error.message;else{await loadCelebrity();renderCelebrityAdmin();$("#celebrityAdminMsg").textContent="All celebrity articles are published on the website."}}});
document.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;if(b.dataset.tab){document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active")}if(b.dataset.open){document.querySelector('[data-tab="'+b.dataset.open+'"]').click()}if(b.id==="refreshBtn")await refresh();if(b.id==="saveHomepageBtn")await saveHomepage();if(b.id==="addSectionBtn")await addHomepageSection();if(b.id==="newStoryBtn")storyEditor();if(b.id==="newPersonBtn")personEditor();if(b.id==="newAdBtn")adEditor();if(b.dataset.editStory)storyEditor(state.stories.find(x=>x.id===b.dataset.editStory));if(b.dataset.editPerson)personEditor(state.people.find(x=>x.id===b.dataset.editPerson));if(b.dataset.editAd)adEditor(state.ads.find(x=>x.id===b.dataset.editAd));if(b.dataset.toggleStory){const x=state.stories.find(x=>x.id===b.dataset.toggleStory);await toggle("posts",x.id,"is_published",!x.is_published);if(!x.is_published)await toggle("posts",x.id,"published_at",new Date().toISOString())}if(b.dataset.deleteStory){if(confirm("Delete this story?")){const r=await db.from("posts").delete().eq("id",b.dataset.deleteStory);if(r.error)alert(r.error.message);else await refresh()}}if(b.dataset.togglePerson){const x=state.people.find(x=>x.id===b.dataset.togglePerson);await toggle("people_profiles",x.id,"is_published",!x.is_published)}if(b.dataset.verifyPerson){const x=state.people.find(x=>x.id===b.dataset.verifyPerson);await db.from("people_profiles").update({is_verified:!x.is_verified,verified_at:!x.is_verified?new Date().toISOString():null,verified_label:!x.is_verified?"Verified by Naija Newspaper":null}).eq("id",x.id);await refresh()}if(b.dataset.removeSection){const row=b.closest("[data-section-id]");if(row){await db.from("homepage_sections").update({enabled:false,updated_at:new Date().toISOString()}).eq("id",row.dataset.sectionId);await refresh()}}if(b.dataset.sub)await reviewSubmission(b.dataset.sub);if(b.dataset.claim)await reviewClaim(b.dataset.claim);if(b.id==="uploadBtn")uploadMedia()});
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget;$("#loginMsg").textContent="";const r=await db.auth.signInWithPassword({email:f.email.value.trim(),password:f.password.value});if(r.error)$("#loginMsg").textContent=r.error.message;else await boot()});
$("#logoutBtn").onclick=async()=>{await db.auth.signOut();showLogin()};
$("#uploadBtn").onclick=uploadMedia;
async function uploadMedia(){const file=$("#mediaFile").files[0];if(!file)return alert("Choose a file first.");const clean=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-");const path=Date.now()+"-"+clean;$("#uploadMsg").textContent="Uploading…";const r=await db.storage.from("naija-media").upload(path,file,{cacheControl:"3600",upsert:false});if(r.error){$("#uploadMsg").textContent=r.error.message;return}$("#uploadMsg").textContent="Uploaded successfully.";$("#mediaFile").value="";renderMedia()}
$("#saveSettingsBtn").onclick=async()=>{const inputs=[...document.querySelectorAll("[data-setting]")];for(const i of inputs){const r=await db.from("site_settings").update({setting_value:i.value,updated_at:new Date().toISOString()}).eq("setting_key",i.dataset.setting);if(r.error){$("#settingsMsg").textContent=r.error.message;return}}$("#settingsMsg").textContent="Settings saved.";await loadSettings();renderSettings()};
boot();