import fs from "node:fs/promises";import path from "node:path";
const U="https://dprulohylwgzmetgrywj.supabase.co",K="sb_publishable_gNWkc787SxA7U76No3A4kg_XHP0x2j4",B="https://kharviefx-tech.github.io/naija-newspaper";
const e=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])),s=v=>String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),d=v=>v?new Date(v).toLocaleDateString("en-NG",{year:"numeric",month:"long",day:"numeric"}):"";
async function q(t,p){let r=await fetch(U+"/rest/v1/"+t+"?"+p,{headers:{apikey:K,Authorization:"Bearer "+K}});if(!r.ok)throw Error(await r.text());return r.json()}
const out=process.argv[2]||".";await fs.mkdir(path.join(out,"people"),{recursive:true});await fs.mkdir(path.join(out,"story"),{recursive:true});
const [people,posts]=await Promise.all([q("people_profiles","select=*&is_published=eq.true&order=display_name.asc"),q("posts","select=*&is_published=eq.true&order=published_at.desc")]);
const urls=[B+"/"];const paras=t=>String(t||"").split(/\n{2,}/).filter(Boolean).map(x=>"<p>"+e(x).replace(/\n/g,"<br>")+"</p>").join("");
function page(title,desc,canon,type,data,body){return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+'</title><meta name="description" content="'+e(desc)+'"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="'+e(canon)+'"><link rel="stylesheet" href="/naija-newspaper/styles.css"><script type="application/ld+json">'+JSON.stringify({"@context":"https://schema.org","@type":type,...data}).replace(/</g,"\\u003c")+'</script></head><body><header class="site-head"><div class="wrap masthead"><a class="brand" href="/naija-newspaper/">NAIJA <b>NEWSPAPER</b></a></div></header><main class="wrap section">'+body+'</main><footer class="footer"><div class="wrap footer-bottom">© '+new Date().getFullYear()+' Naija Newspaper. All rights reserved.</div></footer></body></html>'}
for(const p of people){let z=s(p.slug||p.display_name);if(!z)continue;let c=B+"/people/"+z+"/",body='<article class="article-view"><div class="section-kicker">PEOPLE PROFILE</div><h1 class="profile-name">'+e(p.display_name)+'</h1><p class="profile-headline">'+e(p.headline||p.category||p.person_type||"Public profile")+'</p>'+(p.is_verified?'<span class="verified">✓ Verified by Naija Newspaper</span>':"")+(p.profile_image_url?'<img class="article-hero" src="'+e(p.profile_image_url)+'" alt="'+e(p.display_name)+'">':"")+'<h2>Biography</h2><div class="article-content">'+paras(p.bio||p.short_bio||"This profile is being developed.")+'</div>'+(p.official_website_url?'<p><a class="read-link" href="'+e(p.official_website_url)+'" rel="noopener">Official website →</a></p>':"")+'<p><a class="read-link" href="/naija-newspaper/#claim">Claim or request an update →</a></p></article>';await fs.mkdir(path.join(out,"people",z),{recursive:true});await fs.writeFile(path.join(out,"people",z,"index.html"),page((p.meta_title||p.display_name)+" — Naija Newspaper",p.meta_description||p.short_bio||p.headline||"People profile on Naija Newspaper",c,"Person",{name:p.display_name,description:p.bio||p.short_bio,image:p.profile_image_url||undefined,url:c,sameAs:Array.isArray(p.same_as)?p.same_as:[]},body));urls.push(c)}
for(const x of posts){let z=s(x.slug||x.title);if(!z)continue;let c=B+"/story/"+z+"/",body='<article class="article-view"><div class="section-kicker">'+e(x.content_type||"NEWS")+'</div><h1>'+e(x.title||"Untitled story")+'</h1><div class="article-meta">Published '+e(d(x.published_at))+(x.sponsored?" · Sponsored":"")+'</div>'+(x.featured_image_url?'<img class="article-hero" src="'+e(x.featured_image_url)+'" alt="'+e(x.title||"Story")+'">':"")+(x.excerpt?'<p class="article-dek">'+e(x.excerpt)+'</p>':"")+'<div class="article-content">'+paras(x.content||"")+'</div><p><a class="read-link" href="/naija-newspaper/">← Back to Naija Newspaper</a></p></article>';await fs.mkdir(path.join(out,"story",z),{recursive:true});await fs.writeFile(path.join(out,"story",z,"index.html"),page((x.meta_title||x.title)+" — Naija Newspaper",x.meta_description||x.excerpt||"Naija Newspaper story",c,"NewsArticle",{headline:x.title,datePublished:x.published_at,dateModified:x.updated_at||x.published_at,url:c,author:{"@type":"Organization",name:"Naija Newspaper"}},body));urls.push(c)}
await fs.writeFile(path.join(out,"sitemap.xml"),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>"<url><loc>"+e(u)+"</loc></url>").join("")+"</urlset>");console.log("Generated",people.length,"people pages and",posts.length,"story pages");